Web/monitorsite/monitor/urls.py
from django.urls import path, re_path

from . import views

app_name = 'monitor'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddMonitorView.as_view(), name='add'),
    path('graph/', views.GraphView.as_view(), name='graph'),
    re_path(r'^device/(?P<device_id>[0-9a-fA-F]+)$',
            views.DetailView.as_view(), name='detail'),
]

Web/monitorsite/monitorsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings

extra_context = {}

urlpatterns = [
    path('monitor/', include('monitor.urls'), name='monitor'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
         template_name='monitor/login.html',
         extra_context=extra_context), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
          template_name='monitor/logout.html',
         extra_context=extra_context), name='logout'),
    path('', RedirectView.as_view(pattern_name='monitor:index'), name='root'),
]

Web/monitorsite/monitor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from uuid import uuid4
import json
import paho.mqtt.publish

# Create your models here.
DEFAULT_USER = 'parked_device_user'


def get_parked_user():
    return get_user_model().objects.get_or_create(username=DEFAULT_USER)[0]


def generate_association_code():
    return uuid4().hex


def default_averages():
    return { "hours": [0] * 24 }

class Monitor(models.Model):
    name = models.CharField(max_length=50, default="New Monitor")
    device_id = models.CharField(db_index=True,
                                 max_length=12,
                                 primary_key=True)
    user = models.ForeignKey(User, db_index=True,
                             on_delete=models.SET(get_parked_user))
    association_code = models.CharField(max_length=32, unique=True,
                                        default=generate_association_code)
    created_at = models.DateTimeField(auto_now_add=True)

    averages = models.JSONField(null=True, default=default_averages)

    def __str__(self):
        return "{}: {}".format(self.device_id, self.name)

    def update_averages(self, hour, wattage):
        if hour not in range(24):
            return

        if self.averages["hours"][hour] == 0:
            self.averages["hours"][hour] == wattage
        else:
            # calculating the new average as an exponential recency weighted average (ERWA)
            # This favors more recent data, which makes sense for energy usage, and allows us
            # to save just the average instead of a large amount of historical data.
            new_erwa = self.averages["hours"][hour] * .8 + wattage * .2
            self.averages["hours"][hour] = new_erwa
            self.save()

    def _generate_averages_topic(self):
        return f'devices/{self.device_id}/monitor/average'

    def publish_average_msg(self, hour):
        average_msg = { "hour": hour, "wattage": self.averages["hours"][hour] }
        paho.mqtt.publish.single(self._generate_averages_topic(),
                                 json.dumps(average_msg),
                                 qos=1,
                                 retain=True,
                                 port=50001)

    def _generate_device_association_topic(self):
        return 'devices/{}/lamp/associated'.format(self.device_id)

    def publish_unassociated_msg(self):
        # send association MQTT message
        assoc_msg = {}
        assoc_msg['associated'] = False
        assoc_msg['code'] = self.association_code
        paho.mqtt.publish.single(
            self._generate_device_association_topic(),
            json.dumps(assoc_msg),
            qos=2,
            retain=True,
            port=50001,
            )

    def associate_and_publish_associated_msg(self,  user):
        # update Lampi instance with new user
        self.user = user
        self.save()
        # publish associated message
        assoc_msg = {}
        assoc_msg['associated'] = True
        paho.mqtt.publish.single(
            self._generate_device_association_topic(),
            json.dumps(assoc_msg),
            qos=2,
            retain=True,
            port=50001,
            )

Web/monitorsite/monitor/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import Monitor


class AddMonitorForm(forms.Form):
    association_code = forms.CharField(label="Association Code", min_length=6,
                                       max_length=6)

    def clean(self):
        cleaned_data = super(AddMonitorForm, self).clean()
        print("received form with code {}".format(
              cleaned_data['association_code']))
        # look up device with start of association_code
        uname = settings.DEFAULT_USER
        parked_user = get_user_model().objects.get(username=uname)
        devices = Monitor.objects.filter(
            user=parked_user,
            association_code__startswith=cleaned_data['association_code'])
        if not devices:
            self.add_error('association_code',
                           ValidationError("Invalid Association Code",
                                           code='invalid'))
        else:
            cleaned_data['device'] = devices[0]
        return cleaned_data

Web/monitorsite/monitor/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Monitor
from django.conf import settings
from monitor.forms import AddMonitorForm

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'monitor/index.html'

    def get_queryset(self):
        results = Monitor.objects.filter(user=self.request.user)
        return results

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context


class DetailView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'monitor/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['device'] = get_object_or_404(
            Monitor, pk=kwargs['device_id'], user=self.request.user)
        return context


class GraphView(LoginRequiredMixin, generic.ListView):
    template_name = 'monitor/graph.html'

    def get_queryset(self):
        results = Monitor.objects.filter(user=self.request.user)
        return results

    def get_context_data(self, **kwargs):
        context = super(GraphView, self).get_context_data(**kwargs)
        return context


class AddMonitorView(LoginRequiredMixin, generic.FormView):
    template_name = 'monitor/addmonitor.html'
    form_class = AddMonitorForm
    success_url = '/monitor'

    def get_context_data(self, **kwargs):
        context = super(AddMonitorView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        device = form.cleaned_data['device']
        device.associate_and_publish_associated_msg(self.request.user)

        return super(AddMonitorView, self).form_valid(form)

Web/monitorsite/monitor/templates/monitor/addmonitor.html
{% extends "monitor/base.html" %}

{% block title %}Add new Monitor{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Monitor" />
</form>
{% endblock %}

Web/monitorsite/monitor/templates/monitor/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Outlet Energy Monitor{% endblock %}</title>

  <meta charset="utf-8">
  <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">

  <link rel="stylesheet" type="text/css" href="{% static 'monitor/css/site.css' %}"/>

    {% block additional_head_content %}
    {% endblock %}

</head>
<body>
    <div id="outer-pane" class="centered-root">
         <div>
            {% if user.is_authenticated %}
               <a href="{% url 'logout' %}">Logout</a>
               {% if user.is_superuser %}
                   <a href="{% url 'admin:index' %}">Admin</a>
               {% endif %}
            {% else %}
               <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
        {% block content %}
        <p>Content Goes Here.</p>
        {% endblock %}
    </div>
</body>
</html>

Web/monitorsite/monitor/templates/monitor/detail.html
{% extends "monitor/base.html" %}
{% load static %}

{% block title %}Monitor{% endblock %}

{% block additional_head_content %}
  <meta name="description" content="Monitor Control for {{ device.device_id }}">
{% endblock %}

{% block content %}
    <script type="text/javascript">
        var window_global = {};
        window_global['session_key'] = "{{ request.session.session_key }}";
        window_global['device_id'] = "{{ device.device_id }}";
        window_global['mqtt'] = {'hostname': window.location.hostname,
                                'websockets_port': 50002};
    </script>
	<div id="top-pane">
	    <span id="time-text">00:00:00 AM</span>
	    <span id="wattage-text">0 W</span>
	    <span id="diff-text">± 0 W</span>
	</div>
	<div id="bottom-pane">
	</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.2/mqttws31.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js" type="text/javascript"></script>

    <script src="{% static 'monitor/js/websockets.js' %}" type="text/javascript"></script>
    <script src="{% static 'monitor/js/tinycolor.js' %}" type="text/javascript"></script>

{% endblock %}

Web/monitorsite/monitor/templates/monitor/graph.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Energy Usage Graph</title>

  <meta charset="utf-8">
  <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">

  <link rel="stylesheet" type="text/css" href="{% static 'monitor/css/site.css' %}"/>

</head>
<body>
    <script type="text/javascript">
	const window_global = { 'labels': {}, 'averages': {} };
        window_global['mqtt'] = {'hostname': window.location.hostname,
                                'websockets_port': 50002};
    </script>
{% for monitor in monitor_list %}
    <script type="text/javascript">
	window_global['labels']['{{ monitor.device_id }}'] = "{{ monitor.name }}";
	window_global['averages']['{{ monitor.device_id }}'] = {{ monitor.averages.hours }};
    </script>
{% endfor %}

    <div id="graph-pane" class="centered-root">
        <div>
            {% if user.is_authenticated %}
               <a href="{% url 'logout' %}">Logout</a>
               {% if user.is_superuser %}
                   <a href="{% url 'admin:index' %}">Admin</a>
               {% endif %}
            {% else %}
               <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>

	{% if monitor_list %}
	    <h2 id="graph-header">Total Current Usage: 0 W</h2>
	    <div id="graph-container"><canvas id="graph" style="width: 100%; height: 100%;"></canvas></div>
	{% else %}
	    <h2 id="graph-header">No data (no Monitors associated with your user).</h2>
	{% endif %}
    </div>

    {% if monitor_list %}
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.2/mqttws31.js" type="text/javascript"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js" type="text/javascript"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.1.1/chart.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.1.1/helpers.esm.min.js"></script>
    	<script src="{% static 'monitor/js/graph.js' %}" type="text/javascript"></script>
    {% endif %}
</body>
</html>

Web/monitorsite/monitor/templates/monitor/index.html
{% extends "monitor/base.html" %}

{% block content %}

{% if monitor_list %}
    <ul>
    {% for device in monitor_list %}
       <li><a href="{% url 'monitor:detail' device.device_id %}">
        {{ device.name }} {{device.device_id }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'monitor:graph' %}">Your Usage Graph</a>
    <br/>
    <a href="{% url 'monitor:add' %}">Add a new Monitor</a>
{% else %}
    <p>No devices are available.</p>
    <a href="{% url 'monitor:add' %}">Add a new Monitor</a>
{% endif %}

{% endblock %}

Web/monitorsite/monitor/templates/monitor/login.html
{% extends "monitor/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Web/monitorsite/monitor/templates/monitor/logout.html
{% extends "monitor/base.html" %}

{% block title %}Logged Out{% endblock %}

{% block content %}
  <p>Logged out</p>
{% endblock %}